config/routes.rb
Bookshelf::Application.routes.draw do
  resources :orders

  devise_for :users

  resources :books
  match '/books/comment' => "books#comment"
  
  root :to => "books#index"

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :comments
  has_many :orders
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :ldap_check_auth, #:registerable,
         #:recoverable, 
         :rememberable, :trackable#, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :login, :username, :remember_me
  
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from DeviseLdapCheckAuth::LdapException do |exception|
    render :text => exception, :status => 500
    end
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, :notice => 'Book was successfully created.' }
        format.json { render :json => @book, :status => :created, :location => @book }
      else
        format.html { render :action => "new" }
        format.json { render :json => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, :notice => 'Book was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :ok }
    end
  end
  
  # POST /books/comment
  def comment
    if user_signed_in?
      comment = Book.find(params[:id]).comments.new(params[:comment])
      comment.user = current_user
      comment.save
      flash[:notice] = "Comment added"
      redirect_to :action => "show", :id => params[:id]
    else
      flash[:alert] = "Not signed in"
      redirect_to :action => "show", :id => params[:id]
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, :notice => 'Order was successfully created.' }
        format.json { render :json => @order, :status => :created, :location => @order }
      else
        format.html { render :action => "new" }
        format.json { render :json => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, :notice => 'Order was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/books/_book.html.erb
  <tr>
    <td><%= book.inv_number %></td>
    <td><%= image_tag(book.img_url, :height => 100) %></td>
    <td><%= link_to book.author, book %></td>
    <td><%= book.name %></td>
    <td><%= book.free_count %></td>
    <td>
      <table>
          <% for order in book.orders %>
            <tr>
              <td> <%= mail_to order.user.email, order.user.username %> </td>
              <td> <%= order.date_from.to_s %> </td>
              <td> <%= order.date_to.to_s %> </td>
            </tr>
          <% end %>
      </table>
    </td>
  </tr>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :inv_number %><br />
    <%= f.number_field :inv_number %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br />
    <%= f.text_field :img_url %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :free_count %><br />
    <%= f.number_field :free_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_header.html.erb
<table border="1px" cellspacing="1" cellpadding="1" width="100%" style="text-align: center">
  <tr>
    <th>Inv number</th>
    <th>Img url</th>
    <th>Author</th>
    <th>Name</th>
    <th>Free count</th>
    <th>Orders</th>
  </tr>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<%= render "header" %>

<%= render :partial => "book", :collection => @books %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<%= render "header" %>
<%= render :partial => "book", :locals => { :book => @book } %>
</table>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

<h2>Comments</h2>

<%= "No comments :(" if @book.comments.empty? %>

<% for comment in @book.comments %>
  <%= comment.body %>
  <%= comment.user.username %>
  <hr />
<% end %>

<% if user_signed_in? %>

	<%= form_tag :action => "comment", :id => @book %>
	  <%= text_area "comment", "body" %><br />
	  <%= submit_tag "Comment!" %>
	</form>
	<%= link_to "Выйти", destroy_user_session_path, method: :delete %>
<% else %>

	<p>You are not authorized to comment</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookshelf</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p id="notice" class="notice"><%= notice %></p>
  <p id="alert" class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @order.id %>
</p>

<p>
  <b>Book:</b>
  <%= @order.book.author + " - " + @order.book.name %>
</p>

<p>
  <b>User:</b>
  <%= @order.user.email %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>